In [17]:
import numpy as np
import matplotlib.pyplot as plt

In [18]:
x = np.array([1,2,3,4,5])
y = np.array([1,3,5,3,7])

N = len(x)

In [19]:
# Calculate Mean
mu_x = np.mean(x)
mu_y = np.mean(y)
print(mu_x)
print(mu_y)

3.0
3.8


In [20]:
#Calculate Sigma
x_tilde = x-mu_x
y_tilde = y-mu_y
tildes = np.vstack((x_tilde.T,y_tilde.T))
sigma = np.dot(tildes,tildes.T)/N

print(x_tilde)
print(y_tilde)
print(x_tilde.T.shape)
print(y_tilde.T.shape)
print(tildes)
print(tildes.shape)
print(sigma)

[-2. -1.  0.  1.  2.]
[-2.8 -0.8  1.2 -0.8  3.2]
(5,)
(5,)
[[-2.  -1.   0.   1.   2. ]
 [-2.8 -0.8  1.2 -0.8  3.2]]
(2, 5)
[[2.   2.4 ]
 [2.4  4.16]]


In [21]:
#Diagonalization
lamdas,q = np.linalg.eig(sigma) #Eigenvalues,Eigenvectors = np.linalg.eig(sigma)
print(lamdas)
print(q)

[0.44819454 5.71180546]
[[-0.83975136 -0.54297114]
 [ 0.54297114 -0.83975136]]
